dolphin:
	cargo run -- -q /data/kyclark/dolphin/test/ -d /data/kyclark/uproc/db -m /data/kyclark/uproc/model

empty:
	cargo run -- -q /data/kyclark/dolphin/empty/ -d /data/kyclark/uproc/db -m /data/kyclark/uproc/model


alise:
	cargo run -- -q /Users/aponsero/Documents/UA_POSTDOC/papers/data_saving/FIGURES_submission_gigascience/raw_sets/Figure2/reference_genomes
